from poke_env.battle.effect import Effect
from poke_env.battle.status import Status

POKEMON = {
    "liquidation,lastrespects,aquajet,protect": 1,
    "superfang,feint,followme,protect": 2,
    "scaleshot,haze,tailwind,protect": 3,
    "flareblitz,knockoff,fakeout,partingshot": 4,
    "vacuumwave,earthpower,hypervoice,bloodmoon": 5,
    "makeitrain,shadowball,powergem,trick": 6,
    "expandingforce,dazzlinggleam,terablast,trickroom": 7,
    "psychic,followme,helpinghand,trickroom": 8,
    "eruption,heatwave,earthpower,weatherball": 9,
    "facade,earthquake,headlongrush,protect": 10,
    "sacredsword,psychocut,wideguard,trickroom": 11,
    "populationbomb,followme,taunt,protect": 12,
    "scaleshot,tailwind,haze,protect": 13,
    "makeitrain,shadowball,nastyplot,protect": 14,
    "bloodmoon,earthpower,hypervoice,vacuumwave": 15,
    "drainpunch,ragefist,bulkup,protect": 16,
    "superfang,beatup,followme,protect": 17,
    "woodhammer,grassyglide,highhorsepower,fakeout": 18,
    "tailwind,moonblast,encore,faketears": 19,
    "makeitrain,shadowball,thunderbolt,powergem": 20,
    "icywind,weatherball,muddywater,hurricane": 21,
    "fakeout,grassyglide,woodhammer,taunt": 22,
    "scaleshot,lowkick,protect,tailwind": 23,
    "electroshot,dracometeor,flashcannon,protect": 24,
    "nastyplot,makeitrain,shadowball,protect": 25,
    "closecombat,direclaw,coaching,protect": 26,
    "fakeout,grassyglide,drumbeating,highhorsepower": 27,
    "scaleshot,stompingtantrum,tailwind,protect": 28,
    "blizzard,icywind,encore,auroraveil": 29,
    "rockslide,flareblitz,extremespeed,protect": 30,
    "kowtowcleave,suckerpunch,swordsdance,protect": 31,
    "woodhammer,grassyglide,uturn,fakeout": 32,
    "followme,helpinghand,moonblast,protect": 33,
    "heatwave,gigadrain,quiverdance,protect": 34,
    "protect,fakeout,closecombat,direclaw": 35,
    "liquidation,fissure,yawn,curse": 36,
}

POKEMON_DESCRIPTION = {
    1: "Basculegion with Adaptability, which boosts STAB moves from 1.5x to 2x. Max Attack and Speed with an Adamant nature maximizes its offensive presence. Tera Ghost further boosts Last Respects.",
    2: "Maushold-Four with Friend Guard, which reduces damage to allies by 25%. Max HP and significant investment in Defense and Special Defense with a Jolly nature make it a bulky supporter.",
    3: "Dragonite with Multiscale, which halves damage taken when at full HP. Max Speed and high Attack with a Jolly nature make it a fast and powerful attacker.",
    4: "Incineroar with Intimidate, which lowers the opponent's Attack by one stage. Significant investment in HP and Special Defense with a Jolly nature makes it a bulky pivot that can switch in and weaken physical attackers.",
    5: "Ursaluna-Bloodmoon with Mind's Eye, which allows it to hit Ghost-types with Normal- and Fighting-type moves and ignore accuracy checks. Investment in HP, Special Attack, and Special Defense with a Modest nature makes it a bulky special attacker.",
    6: "Gholdengo with Good as Gold, which makes it immune to status moves. Investment in HP, Defense, Special Attack, and Special Defense with a Modest nature makes it a versatile and bulky special attacker.",
    7: "Hatterene with Magic Bounce, which reflects status moves back to the user. Max HP and Special Attack with a Quiet nature and 0 Speed IVs make it a powerful Trick Room attacker.",
    8: "Indeedee-F with Psychic Surge, which sets up Psychic Terrain when it enters the battle. Max Defense and significant investment in HP with a Relaxed nature and 0 Speed IVs make it a bulky Trick Room setter and supporter.",
    9: "Torkoal with Drought, which sets up sun when it enters the battle. Max HP and Special Attack with a Quiet nature and 0 Speed IVs make it a powerful Trick Room attacker that can abuse sun-boosted Fire-type moves.",
    10: "Ursaluna with Guts, which boosts its Attack by 1.5x when it has a status condition. Max HP and Attack with a Brave nature and 0 Speed IVs make it a powerful Trick Room attacker, especially when combined with the Flame Orb.",
    11: "Gallade with Sharpness, which boosts the power of slicing moves by 1.5x. Max Attack and significant investment in HP with a Brave nature and 0 Speed IVs make it a powerful Trick Room attacker.",
    12: "Maushold with Technician, which boosts the power of moves with 60 or less base power by 1.5x. Max Attack and Speed with a Jolly nature make it a fast attacker that can abuse Population Bomb.",
    13: "Dragonite with Multiscale, which halves damage taken when at full HP. Max Speed and high Attack with an Adamant nature make it a fast and powerful attacker.",
    14: "Gholdengo with Good as Gold, which makes it immune to status moves. Max Speed and significant investment in Special Attack and HP with a Timid nature make it a fast special attacker.",
    15: "Ursaluna-Bloodmoon with Mind's Eye, which allows it to hit Ghost-types with Normal- and Fighting-type moves and ignore accuracy checks. Investment in HP, Special Attack, and Special Defense with a Modest nature makes it a bulky special attacker.",
    16: "Annihilape with Defiant, which boosts its Attack by two stages when its stats are lowered. Max Speed and significant investment in HP and Attack with a Jolly nature make it a fast and powerful attacker that can punish Intimidate.",
    17: "Maushold-Four with Friend Guard, which reduces damage to allies by 25%. Max HP and significant investment in Defense and Speed with a Jolly nature make it a bulky supporter.",
    18: "Rillaboom with Grassy Surge, which sets up Grassy Terrain when it enters the battle. Significant investment in HP and Attack with an Adamant nature makes it a bulky attacker that can abuse Grassy Glide.",
    19: "Whimsicott with Prankster, which gives its status moves +1 priority. Max Special Attack and Speed with a Timid nature make it a fast supporter that can set up Tailwind or disrupt the opponent with Encore.",
    20: "Gholdengo with Good as Gold, which makes it immune to status moves. Max Speed and Special Attack with a Modest nature make it a fast and powerful special attacker.",
    21: "Pelipper with Drizzle, which sets up rain when it enters the battle. Max Special Attack and Speed with a Timid nature make it a fast special attacker that can abuse rain-boosted Water-type moves.",
    22: "Rillaboom with Grassy Surge, which sets up Grassy Terrain when it enters the battle. Significant investment in HP and Attack with an Adamant nature makes it a bulky attacker that can abuse Grassy Glide.",
    23: "Dragonite with Multiscale, which halves damage taken when at full HP. Max Attack and Speed with an Adamant nature make it a powerful and fast attacker.",
    24: "Archaludon with Sturdy, which allows it to survive a hit that would otherwise KO it with 1 HP if it has full HP. Max Special Attack and Speed with a Timid nature make it a fast special attacker.",
    25: "Gholdengo with Good as Gold, which makes it immune to status moves. Significant investment in HP and Speed with a Modest nature make it a fast and bulky special attacker.",
    26: "Sneasler with Unburden, which doubles its Speed when it loses its held item. Investment in HP, Attack, and Speed with an Adamant nature makes it a fast physical attacker, especially after its White Herb is consumed.",
    27: "Rillaboom with Grassy Surge, which sets up Grassy Terrain when it enters the battle. Max Speed and significant investment in Attack and HP with a Jolly nature make it a fast and bulky attacker.",
    28: "Dragonite with Multiscale, which halves damage taken when at full HP. Max Attack and Speed with an Adamant nature make it a powerful and fast attacker.",
    29: "Ninetales-Alola with Snow Warning, which sets up snow when it enters the battle. Max Special Attack and Speed with a Timid nature make it a fast special attacker that can set up Aurora Veil.",
    30: "Arcanine-Hisui with Intimidate, which lowers the opponent's Attack by one stage. Max Attack and Speed with a Jolly nature make it a fast physical attacker that can weaken opposing physical threats.",
    31: "Kingambit with Defiant, which boosts its Attack by two stages when its stats are lowered. Max HP and Attack with an Adamant nature make it a bulky and powerful attacker that can punish Intimidate.",
    32: "Rillaboom with Grassy Surge, which sets up Grassy Terrain when it enters the battle. Max HP and significant investment in Attack and Special Defense with an Adamant nature make it a bulky attacker that can abuse Grassy Glide.",
    33: "Clefable with Unaware, which ignores the opponent's stat changes when attacking. Max HP and Defense with a Bold nature make it a very bulky supporter that can't be easily broken by setup sweepers.",
    34: "Volcarona with Flame Body, which has a 30% chance to burn an attacker that makes contact. Significant investment in HP, Defense, and Speed with a Modest nature make it a bulky setup sweeper.",
    35: "Sneasler with Unburden, which doubles its Speed when it loses its held item. Max Speed and significant investment in HP and Attack with an Adamant nature makes it a fast physical attacker, especially after its Grassy Seed is consumed.",
    36: "Dondozo with Unaware, which ignores the opponent's stat changes when attacking. Max HP and Special Defense with a Careful nature make it a very bulky wall that can't be easily broken by setup sweepers.",
}

ITEM_DESCRIPTION = {
    "focussash": "Holds Focus Sash. If the holder has full HP, it survives a hit that would otherwise KO it with 1 HP. Single use. This is useful for frail pokemon to guarantee they can get off at least one move.",
    "rockyhelmet": "Holds Rocky Helmet. If the holder is hit by a contact move, the attacker loses 1/6 of its maximum HP. This is useful to punish physical attackers.",
    "loadeddice": "Holds Loaded Dice. The holder's multi-hit moves are more likely to hit more times. This is useful for Dragonite with Scale Shot to maximize its damage output.",
    "safetygoggles": "Holds Safety Goggles. The holder is immune to powder moves and damage from Sandstorm or Hail. This is useful to avoid moves like Spore, Rage Powder or Sleep Powder.",
    "assaultvest": "Holds Assault Vest. The holder's Special Defense is 1.5x, but it can only select damaging moves. This is useful to make Pokemon tank special attacks.",
    "choicespecs": "Holds Choice Specs. The holder's Special Attack is 1.5x, but it can only select the first move it executes. This is useful to threaten immediate large damage.",
    "covertcloak": "Holds Covert Cloak. The holder is immune to the additional effects of other Pokemon's moves. This is useful to avoid flinching from Fake out or stat drops.",
    "psychicseed": "Holds Psychic Seed. If the terrain is Psychic Terrain, consumes the seed to raise the holder's Special Defense by 1 stage. This is useful when paired with a Psychic Terrain setter.",
    "flameorb": "Holds Flame Orb. At the end of each turn, this item attempts to burn the holder. This is useful for Ursaluna with the Guts ability, which boosts its Attack when it has a status condition.",
    "clearamulet": "Holds Clear Amulet. Prevents other Pokemon from lowering the holder's stats. This is useful to avoid being weakened by abilities like Intimidate.",
    "widelens": "Holds Wide Lens. The accuracy of the holder's moves is 1.1x. This is useful to increase consistency of inaccurate moves.",
    "lifeorb": "Holds Life Orb. The holder's attacks do 1.3x damage, but it loses 1/10 of its max HP after each attack. This is useful to get a significant boost in damage output.",
    "sitrusberry": "Holds Sitrus Berry. Restores 1/4 of the holder's max HP when its HP is below 1/2. Single use. This is useful on bulky pokemon to increase survivability.",
    "miracleseed": "Holds Miracle Seed. The holder's Grass-type moves have 1.2x power. This is useful for grass pokemon to boost the power of its STAB moves.",
    "choicescarf": "Holds Choice Scarf. The holder's Speed is 1.5x, but it can only select the first move it executes. This is useful for Pelipper to outspeed and revenge kill faster threats.",
    "powerherb": "Holds Power Herb. The holder's two-turn moves complete in one turn. Single use. This is useful for Archaludon to use Electro Shot immediately.",
    "grassyseed": "Holds Grassy Seed. If the terrain is Grassy Terrain, consumes the seed to raise the holder's Defense by 1 stage. This is useful when paired with a Grassy Terrain setter.",
    "whiteherb": "Holds White Herb. If any of the holder's stats are lowered, consumes the herb to restore them to normal. Single use. This is useful to counteract the stat drops from Close Combat and other moves.",
    "blackglasses": "Holds Black Glasses. The holder's Dark-type moves have 1.2x power. This is useful for dark type pokemon to boost the power of its STAB moves.",
    "leftovers": "Holds Leftovers. At the end of each turn, the holder restores 1/16 of its maximum HP. This is useful for bulky pokemon to increase its longevity.",
}

STATUS_DESCRIPTION = {
    Status.BRN: "This pokemon is burned. Burn reduces the Pokemon's Attack stat by 50% and causes them to lose 6.25% of their maximum HP at the end of each turn. Fire-type Pokemon cannot be burned",
    Status.FNT: "The Pokemon has 0 HP and cannot battle. Fainted Pokemon must be switched out and cannot use moves or take actions until revived.",
    Status.FRZ: "This pokemon is frozen. Freeze causes the pokemon to not move. Has a 20% chance to thaw each turn, and will immediately thaw if hit by a Fire-type move. Ice-type Pokemon cannot be frozen.",
    Status.PAR: "This pokemon is paralysed. Paralysis reduces the Pokemon's Speed stat by 50% and gives them a 25% chance to be fully paralyzed (unable to move) each turn. Electric-type Pokemon cannot be paralyzed.",
    Status.PSN: "This pokemon is poisoned. Poison causes the Pokemon to lose 12.5% of their maximum HP at the end of each turn. Poison and Steel-type Pokemon cannot be poisoned.",
    Status.SLP: "This pokemon is asleep. Sleep prevents the Pokemon from using moves for 1-3 turns (duration chosen randomly). The Pokemon will wake up automatically when the sleep duration ends or are cured by a move.",
    Status.TOX: "This poison is badly poisoned. It causes the pokemon to take increasing damage each turn: 6.25% max HP on turn 1, then 12.5%, then 18.75%, and so on. The damage counter resets if the Pokemon switches out.",
}

EFFECT_DESCRIPTION = {
    Effect.CONFUSION: "Pokemon is confused and has a 33% chance to hurt itself instead of using moves. Lasts 2-5 turns.",
    Effect.TAUNT: "Pokemon has been taunted. It can only use damaging moves for 3 turns.",
    Effect.ENCORE: "Pokemon is forced to repeat the last used move for 3 turns.",
    Effect.YAWN: "Pokemon will fall asleep after 1 more turn unless switched out.",
}


MOVES = {
    "liquidation": {
        "base_power": 85,
        "type": "water",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 20, "boosts": {"def": -1}},
    },
    "lastrespects": {
        "base_power": 50,
        "type": "ghost",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_base_power": "50 + 50 * fainted allies",
        "secondary": None,
    },
    "aquajet": {
        "base_power": 40,
        "type": "water",
        "category": "physical",
        "priority": 1,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "protect": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 4,
        "accuracy": True,
        "target": "self",
        "pp": 10,
        "flags": {},
        "stalling_move": True,
        "volatile_status": "protect",
        "secondary": None,
    },
    "superfang": {
        "base_power": 0,
        "type": "normal",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
        "damage_callback": "target.hp / 2",
    },
    "feint": {
        "base_power": 30,
        "type": "normal",
        "category": "physical",
        "priority": 2,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"mirror": 1},
        "secondary": None,
        "breaks_protect": True,
    },
    "followme": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 2,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {},
        "volatile_status": "followme",
        "secondary": None,
    },
    "scaleshot": {
        "base_power": 25,
        "type": "dragon",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1},
        "multihit": [2, 5],
        "self": {"boosts": {"def": -1, "spe": 1}},
        "secondary": None,
    },
    "haze": {
        "base_power": 0,
        "type": "ice",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "all",
        "pp": 30,
        "flags": {"bypasssub": 1},
        "on_hit_field": "clear all boosts",
        "secondary": None,
    },
    "tailwind": {
        "base_power": 0,
        "type": "flying",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "allySide",
        "pp": 15,
        "flags": {"bypasssub": 1},
        "side_condition": "tailwind",
        "secondary": None,
    },
    "flareblitz": {
        "base_power": 120,
        "type": "fire",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "defrost": 1},
        "recoil": [33, 100],
        "secondary": {"chance": 10, "status": "brn"},
    },
    "knockoff": {
        "base_power": 65,
        "type": "dark",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_hit": "knock off item",
        "on_base_power": "if target has item, 1.5x power",
        "secondary": None,
    },
    "fakeout": {
        "base_power": 40,
        "type": "normal",
        "category": "physical",
        "priority": 3,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_try": "check first turn",
        "secondary": {"chance": 100, "volatileStatus": "flinch"},
    },
    "partingshot": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1, "sound": 1, "bypasssub": 1},
        "on_hit": "parting shot",
        "secondary": None,
        "boosts": {"atk": -1, "spa": -1},
        "self_switch": True,
    },
    "vacuumwave": {
        "base_power": 40,
        "type": "fighting",
        "category": "special",
        "priority": 1,
        "accuracy": 100,
        "target": "normal",
        "pp": 30,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": None,
    },
    "earthpower": {
        "base_power": 90,
        "type": "ground",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "secondary": {"chance": 10, "boosts": {"spd": -1}},
    },
    "hypervoice": {
        "base_power": 90,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "sound": 1, "bypasssub": 1},
        "secondary": None,
    },
    "bloodmoon": {
        "base_power": 140,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1, "cantusetwice": 1},
        "secondary": None,
    },
    "makeitrain": {
        "base_power": 120,
        "type": "steel",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "self": {"boosts": {"spa": -1}},
        "secondary": None,
    },
    "shadowball": {
        "base_power": 80,
        "type": "ghost",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"bullet": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 20, "boosts": {"spd": -1}},
    },
    "powergem": {
        "base_power": 80,
        "type": "rock",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": None,
    },
    "trick": {
        "base_power": 0,
        "type": "psychic",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_hit": "swap items",
        "secondary": None,
    },
    "expandingforce": {
        "base_power": 80,
        "type": "psychic",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_base_power": "if psychic terrain, 1.5x power and hits all foes",
        "secondary": None,
    },
    "dazzlinggleam": {
        "base_power": 80,
        "type": "fairy",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "sound": 1},
        "secondary": None,
    },
    "terablast": {
        "base_power": 80,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_modify_type": "if terastallized, becomes tera type",
        "on_modify_move": "if atk > spa and tera type is physical, becomes physical",
        "secondary": None,
    },
    "trickroom": {
        "base_power": 0,
        "type": "psychic",
        "category": "status",
        "priority": -7,
        "accuracy": True,
        "target": "all",
        "pp": 5,
        "flags": {"mirror": 1},
        "pseudo_weather": "trickroom",
        "secondary": None,
    },
    "psychic": {
        "base_power": 90,
        "type": "psychic",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "boosts": {"spd": -1}},
    },
    "helpinghand": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 5,
        "accuracy": True,
        "target": "adjacentAlly",
        "pp": 20,
        "flags": {},
        "volatile_status": "helpinghand",
        "secondary": None,
    },
    "eruption": {
        "base_power": 150,
        "type": "fire",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "on_base_power": "150 * current_hp / max_hp",
        "secondary": None,
    },
    "heatwave": {
        "base_power": 95,
        "type": "fire",
        "category": "special",
        "priority": 0,
        "accuracy": 90,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "status": "brn"},
    },
    "weatherball": {
        "base_power": 50,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"bullet": 1, "protect": 1, "mirror": 1},
        "on_modify_move": "if weather, power doubles and type changes",
        "secondary": None,
    },
    "facade": {
        "base_power": 70,
        "type": "normal",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "if user is poisoned, burned, or paralyzed, power doubles",
        "secondary": None,
    },
    "earthquake": {
        "base_power": 100,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacent",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "secondary": None,
    },
    "headlongrush": {
        "base_power": 120,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "self": {"boosts": {"def": -1, "spd": -1}},
        "secondary": None,
    },
    "sacredsword": {
        "base_power": 90,
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "slicing": 1},
        "ignore_defensive": True,
        "secondary": None,
    },
    "psychocut": {
        "base_power": 70,
        "type": "psychic",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1, "slicing": 1},
        "crit_ratio": 2,
        "secondary": None,
    },
    "wideguard": {
        "base_power": 0,
        "type": "rock",
        "category": "status",
        "priority": 3,
        "accuracy": True,
        "target": "allySide",
        "pp": 10,
        "flags": {"snatch": 1},
        "side_condition": "wideguard",
        "stalling_move": True,
        "secondary": None,
    },
    "populationbomb": {
        "base_power": 20,
        "type": "normal",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "slicing": 1},
        "multihit": 10,
        "secondary": None,
    },
    "taunt": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1, "bypasssub": 1},
        "volatile_status": "taunt",
        "secondary": None,
    },
    "nastyplot": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {"snatch": 1},
        "boosts": {"spa": 2},
        "secondary": None,
    },
    "drainpunch": {
        "base_power": 75,
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "heal": 1},
        "drain": [1, 2],
        "secondary": None,
    },
    "ragefist": {
        "base_power": 50,
        "type": "ghost",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "50 + 50 * times hit",
        "secondary": None,
    },
    "bulkup": {
        "base_power": 0,
        "type": "fighting",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {"snatch": 1},
        "boosts": {"atk": 1, "def": 1},
        "secondary": None,
    },
    "beatup": {
        "base_power": 0,
        "type": "dark",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_modify_move": "hits for each conscious pokemon on user's side",
        "secondary": None,
    },
    "woodhammer": {
        "base_power": 120,
        "type": "grass",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "recoil": [33, 100],
        "secondary": None,
    },
    "grassyglide": {
        "base_power": 55,
        "type": "grass",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_modify_priority": "if grassy terrain, priority is 1",
        "secondary": None,
    },
    "highhorsepower": {
        "base_power": 95,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 95,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "moonblast": {
        "base_power": 95,
        "type": "fairy",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 30, "boosts": {"spa": -1}},
    },
    "encore": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1, "bypasssub": 1},
        "volatile_status": "encore",
        "secondary": None,
    },
    "faketears": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1},
        "boosts": {"spd": -2},
        "secondary": None,
    },
    "thunderbolt": {
        "base_power": 90,
        "type": "electric",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "status": "par"},
    },
    "icywind": {
        "base_power": 55,
        "type": "ice",
        "category": "special",
        "priority": 0,
        "accuracy": 95,
        "target": "allAdjacentFoes",
        "pp": 15,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 100, "boosts": {"spe": -1}},
    },
    "muddywater": {
        "base_power": 90,
        "type": "water",
        "category": "special",
        "priority": 0,
        "accuracy": 85,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "secondary": {"chance": 30, "boosts": {"accuracy": -1}},
    },
    "hurricane": {
        "base_power": 110,
        "type": "flying",
        "category": "special",
        "priority": 0,
        "accuracy": 70,
        "target": "any",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "distance": 1, "wind": 1},
        "on_modify_move": "if rain, accuracy is 100. if sun, 50.",
        "secondary": {"chance": 30, "volatileStatus": "confusion"},
    },
    "lowkick": {
        "base_power": 0,
        "base_power_callback": "based on target's weight",
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "electroshot": {
        "base_power": 130,
        "type": "electric",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"charge": 1, "protect": 1, "mirror": 1},
        "on_try_move": "if not rain, charges 1 turn, boosting SpA. if rain, attacks immediately",
        "secondary": None,
    },
    "dracometeor": {
        "base_power": 130,
        "type": "dragon",
        "category": "special",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "self": {"boosts": {"spa": -2}},
        "secondary": None,
    },
    "flashcannon": {
        "base_power": 80,
        "type": "steel",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "boosts": {"spd": -1}},
    },
    "closecombat": {
        "base_power": 120,
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "self": {"boosts": {"def": -1, "spd": -1}},
        "secondary": None,
    },
    "direclaw": {
        "base_power": 80,
        "type": "poison",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 50, "on_hit": "may poison, paralyze, or sleep target"},
    },
    "coaching": {
        "base_power": 0,
        "type": "fighting",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "adjacentAlly",
        "pp": 10,
        "flags": {"bypasssub": 1},
        "boosts": {"atk": 1, "def": 1},
        "secondary": None,
    },
    "drumbeating": {
        "base_power": 80,
        "type": "grass",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 100, "boosts": {"spe": -1}},
    },
    "stompingtantrum": {
        "base_power": 75,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "if last move failed, power doubles",
        "secondary": None,
    },
    "blizzard": {
        "base_power": 110,
        "type": "ice",
        "category": "special",
        "priority": 0,
        "accuracy": 70,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1, "wind": 1},
        "on_modify_move": "if hail/snow, accuracy is 100",
        "secondary": {"chance": 10, "status": "frz"},
    },
    "auroraveil": {
        "base_power": 0,
        "type": "ice",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "allySide",
        "pp": 20,
        "flags": {"snatch": 1},
        "on_try": "if hail/snow",
        "side_condition": "auroraveil",
        "secondary": None,
    },
    "rockslide": {
        "base_power": 75,
        "type": "rock",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 30, "volatileStatus": "flinch"},
    },
    "extremespeed": {
        "base_power": 80,
        "type": "normal",
        "category": "physical",
        "priority": 2,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "kowtowcleave": {
        "base_power": 85,
        "type": "dark",
        "category": "physical",
        "priority": 0,
        "accuracy": True,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "slicing": 1},
        "secondary": None,
    },
    "suckerpunch": {
        "base_power": 70,
        "type": "dark",
        "category": "physical",
        "priority": 1,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_try": "fails if the target is not preparing an attack",
        "secondary": None,
    },
    "swordsdance": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {"snatch": 1, "dance": 1},
        "boosts": {"atk": 2},
        "secondary": None,
    },
    "uturn": {
        "base_power": 70,
        "type": "bug",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "self_switch": True,
        "secondary": None,
    },
    "gigadrain": {
        "base_power": 75,
        "type": "grass",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "heal": 1},
        "drain": [1, 2],
        "secondary": None,
    },
    "quiverdance": {
        "base_power": 0,
        "type": "bug",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {"snatch": 1, "dance": 1},
        "boosts": {"spa": 1, "spd": 1, "spe": 1},
        "secondary": None,
    },
    "fissure": {
        "base_power": 0,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 30,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "ohko": True,
        "secondary": None,
    },
    "yawn": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1},
        "volatile_status": "yawn",
        "secondary": None,
    },
    "curse": {
        "base_power": 0,
        "type": "ghost",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "normal",
        "pp": 10,
        "flags": {"bypasssub": 1},
        "on_hit": "if user is ghost, target loses 1/4 max hp per turn. else, user loses 1 spe, gains 1 atk, 1 def",
        "secondary": None,
    },
}
