POKEMON = {
    "liquidation,lastrespects,aquajet,protect": 1,
    "superfang,feint,followme,protect": 2,
    "scaleshot,haze,tailwind,protect": 3,
    "flareblitz,knockoff,fakeout,partingshot": 4,
    "vacuumwave,earthpower,hypervoice,bloodmoon": 5,
    "makeitrain,shadowball,powergem,trick": 6,
    "expandingforce,dazzlinggleam,terablast,trickroom": 7,
    "psychic,followme,helpinghand,trickroom": 8,
    "eruption,heatwave,earthpower,weatherball": 9,
    "facade,earthquake,headlongrush,protect": 10,
    "sacredsword,psychocut,wideguard,trickroom": 11,
    "populationbomb,followme,taunt,protect": 12,
    "scaleshot,tailwind,haze,protect": 13,
    "makeitrain,shadowball,nastyplot,protect": 14,
    "bloodmoon,earthpower,hypervoice,vacuumwave": 15,
    "drainpunch,ragefist,bulkup,protect": 16,
    "superfang,beatup,followme,protect": 17,
    "woodhammer,grassyglide,highhorsepower,fakeout": 18,
    "tailwind,moonblast,encore,faketears": 19,
    "makeitrain,shadowball,thunderbolt,powergem": 20,
    "icywind,weatherball,muddywater,hurricane": 21,
    "fakeout,grassyglide,woodhammer,taunt": 22,
    "scaleshot,lowkick,protect,tailwind": 23,
    "electroshot,dracometeor,flashcannon,protect": 24,
    "nastyplot,makeitrain,shadowball,protect": 25,
    "closecombat,direclaw,coaching,protect": 26,
    "fakeout,grassyglide,drumbeating,highhorsepower": 27,
    "scaleshot,stompingtantrum,tailwind,protect": 28,
    "blizzard,icywind,encore,auroraveil": 29,
    "rockslide,flareblitz,extremespeed,protect": 30,
    "dragonclaw,stompingtantrum,earthquake,protect": 31,
    "leafstorm,sleeppowder,encore,tailwind": 32,
    "overheat,burningjealousy,helpinghand,protect": 33,
    "scaleshot,extremespeed,icespinner,protect": 34,
    "ironhead,suckerpunch,assurance,lowkick": 35,
    "eruption,shadowball,heatwave,overheat": 36,
}

POKEMON_DESCRIPTION = {}

ITEM_DESCRIPTION = {}

MOVES = {
    "liquidation": {
        "base_power": 85,
        "type": "water",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 20, "boosts": {"def": -1}},
    },
    "lastrespects": {
        "base_power": 50,
        "type": "ghost",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_base_power": "50 + 50 * fainted allies",
        "secondary": None,
    },
    "aquajet": {
        "base_power": 40,
        "type": "water",
        "category": "physical",
        "priority": 1,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "protect": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 4,
        "accuracy": True,
        "target": "self",
        "pp": 10,
        "flags": {},
        "stalling_move": True,
        "volatile_status": "protect",
        "secondary": None,
    },
    "superfang": {
        "base_power": 0,
        "type": "normal",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
        "damage_callback": "target.hp / 2",
    },
    "feint": {
        "base_power": 30,
        "type": "normal",
        "category": "physical",
        "priority": 2,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"mirror": 1},
        "secondary": None,
        "breaks_protect": True,
    },
    "followme": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 2,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {},
        "volatile_status": "followme",
        "secondary": None,
    },
    "scaleshot": {
        "base_power": 25,
        "type": "dragon",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1},
        "multihit": [2, 5],
        "self": {"boosts": {"def": -1, "spe": 1}},
        "secondary": None,
    },
    "haze": {
        "base_power": 0,
        "type": "ice",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "all",
        "pp": 30,
        "flags": {"bypasssub": 1},
        "on_hit_field": "clear all boosts",
        "secondary": None,
    },
    "tailwind": {
        "base_power": 0,
        "type": "flying",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "allySide",
        "pp": 15,
        "flags": {"bypasssub": 1},
        "side_condition": "tailwind",
        "secondary": None,
    },
    "flareblitz": {
        "base_power": 120,
        "type": "fire",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "defrost": 1},
        "recoil": [33, 100],
        "secondary": {"chance": 10, "status": "brn"},
    },
    "knockoff": {
        "base_power": 65,
        "type": "dark",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_hit": "knock off item",
        "on_base_power": "if target has item, 1.5x power",
        "secondary": None,
    },
    "fakeout": {
        "base_power": 40,
        "type": "normal",
        "category": "physical",
        "priority": 3,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_try": "check first turn",
        "secondary": {"chance": 100, "volatileStatus": "flinch"},
    },
    "partingshot": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1, "sound": 1, "bypasssub": 1},
        "on_hit": "parting shot",
        "secondary": None,
        "boosts": {"atk": -1, "spa": -1},
        "self_switch": True,
    },
    "vacuumwave": {
        "base_power": 40,
        "type": "fighting",
        "category": "special",
        "priority": 1,
        "accuracy": 100,
        "target": "normal",
        "pp": 30,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": None,
    },
    "earthpower": {
        "base_power": 90,
        "type": "ground",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "secondary": {"chance": 10, "boosts": {"spd": -1}},
    },
    "hypervoice": {
        "base_power": 90,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "sound": 1, "bypasssub": 1},
        "secondary": None,
    },
    "bloodmoon": {
        "base_power": 140,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1, "cantusetwice": 1},
        "secondary": None,
    },
    "makeitrain": {
        "base_power": 120,
        "type": "steel",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "self": {"boosts": {"spa": -1}},
        "secondary": None,
    },
    "shadowball": {
        "base_power": 80,
        "type": "ghost",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"bullet": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 20, "boosts": {"spd": -1}},
    },
    "powergem": {
        "base_power": 80,
        "type": "rock",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": None,
    },
    "trick": {
        "base_power": 0,
        "type": "psychic",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_hit": "swap items",
        "secondary": None,
    },
    "expandingforce": {
        "base_power": 80,
        "type": "psychic",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_base_power": "if psychic terrain, 1.5x power and hits all foes",
        "secondary": None,
    },
    "dazzlinggleam": {
        "base_power": 80,
        "type": "fairy",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "sound": 1},
        "secondary": None,
    },
    "terablast": {
        "base_power": 80,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_modify_type": "if terastallized, becomes tera type",
        "on_modify_move": "if atk > spa and tera type is physical, becomes physical",
        "secondary": None,
    },
    "trickroom": {
        "base_power": 0,
        "type": "psychic",
        "category": "status",
        "priority": -7,
        "accuracy": True,
        "target": "all",
        "pp": 5,
        "flags": {"mirror": 1},
        "pseudo_weather": "trickroom",
        "secondary": None,
    },
    "psychic": {
        "base_power": 90,
        "type": "psychic",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "boosts": {"spd": -1}},
    },
    "helpinghand": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 5,
        "accuracy": True,
        "target": "adjacentAlly",
        "pp": 20,
        "flags": {},
        "volatile_status": "helpinghand",
        "secondary": None,
    },
    "eruption": {
        "base_power": 150,
        "type": "fire",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "on_base_power": "150 * current_hp / max_hp",
        "secondary": None,
    },
    "heatwave": {
        "base_power": 95,
        "type": "fire",
        "category": "special",
        "priority": 0,
        "accuracy": 90,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "status": "brn"},
    },
    "weatherball": {
        "base_power": 50,
        "type": "normal",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"bullet": 1, "protect": 1, "mirror": 1},
        "on_modify_move": "if weather, power doubles and type changes",
        "secondary": None,
    },
    "facade": {
        "base_power": 70,
        "type": "normal",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "if user is poisoned, burned, or paralyzed, power doubles",
        "secondary": None,
    },
    "earthquake": {
        "base_power": 100,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacent",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "secondary": None,
    },
    "headlongrush": {
        "base_power": 120,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "self": {"boosts": {"def": -1, "spd": -1}},
        "secondary": None,
    },
    "sacredsword": {
        "base_power": 90,
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "slicing": 1},
        "ignore_defensive": True,
        "secondary": None,
    },
    "psychocut": {
        "base_power": 70,
        "type": "psychic",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "mirror": 1, "slicing": 1},
        "crit_ratio": 2,
        "secondary": None,
    },
    "wideguard": {
        "base_power": 0,
        "type": "rock",
        "category": "status",
        "priority": 3,
        "accuracy": True,
        "target": "allySide",
        "pp": 10,
        "flags": {"snatch": 1},
        "side_condition": "wideguard",
        "stalling_move": True,
        "secondary": None,
    },
    "populationbomb": {
        "base_power": 20,
        "type": "normal",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "slicing": 1},
        "multihit": 10,
        "secondary": None,
    },
    "taunt": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1, "bypasssub": 1},
        "volatile_status": "taunt",
        "secondary": None,
    },
    "nastyplot": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {"snatch": 1},
        "boosts": {"spa": 2},
        "secondary": None,
    },
    "drainpunch": {
        "base_power": 75,
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1, "heal": 1},
        "drain": [1, 2],
        "secondary": None,
    },
    "ragefist": {
        "base_power": 50,
        "type": "ghost",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "50 + 50 * times hit",
        "secondary": None,
    },
    "bulkup": {
        "base_power": 0,
        "type": "fighting",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "self",
        "pp": 20,
        "flags": {"snatch": 1},
        "boosts": {"atk": 1, "def": 1},
        "secondary": None,
    },
    "beatup": {
        "base_power": 0,
        "type": "dark",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "on_modify_move": "hits for each conscious pokemon on user's side",
        "secondary": None,
    },
    "woodhammer": {
        "base_power": 120,
        "type": "grass",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "recoil": [33, 100],
        "secondary": None,
    },
    "grassyglide": {
        "base_power": 55,
        "type": "grass",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_modify_priority": "if grassy terrain, priority is 1",
        "secondary": None,
    },
    "highhorsepower": {
        "base_power": 95,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 95,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "moonblast": {
        "base_power": 95,
        "type": "fairy",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 30, "boosts": {"spa": -1}},
    },
    "encore": {
        "base_power": 0,
        "type": "normal",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1, "bypasssub": 1},
        "volatile_status": "encore",
        "secondary": None,
    },
    "faketears": {
        "base_power": 0,
        "type": "dark",
        "category": "status",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"protect": 1, "reflectable": 1, "mirror": 1},
        "boosts": {"spd": -2},
        "secondary": None,
    },
    "thunderbolt": {
        "base_power": 90,
        "type": "electric",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "status": "par"},
    },
    "icywind": {
        "base_power": 55,
        "type": "ice",
        "category": "special",
        "priority": 0,
        "accuracy": 95,
        "target": "allAdjacentFoes",
        "pp": 15,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 100, "boosts": {"spe": -1}},
    },
    "muddywater": {
        "base_power": 90,
        "type": "water",
        "category": "special",
        "priority": 0,
        "accuracy": 85,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "nonsky": 1},
        "secondary": {"chance": 30, "boosts": {"accuracy": -1}},
    },
    "hurricane": {
        "base_power": 110,
        "type": "flying",
        "category": "special",
        "priority": 0,
        "accuracy": 70,
        "target": "any",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1, "distance": 1, "wind": 1},
        "on_modify_move": "if rain, accuracy is 100. if sun, 50.",
        "secondary": {"chance": 30, "volatileStatus": "confusion"},
    },
    "lowkick": {
        "base_power": 0,
        "base_power_callback": "based on target's weight",
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 20,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "electroshot": {
        "base_power": 130,
        "type": "electric",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"charge": 1, "protect": 1, "mirror": 1},
        "on_try_move": "if not rain, charges 1 turn, boosting SpA. if rain, attacks immediately",
        "secondary": None,
    },
    "dracometeor": {
        "base_power": 130,
        "type": "dragon",
        "category": "special",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "self": {"boosts": {"spa": -2}},
        "secondary": None,
    },
    "flashcannon": {
        "base_power": 80,
        "type": "steel",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 10, "boosts": {"spd": -1}},
    },
    "closecombat": {
        "base_power": 120,
        "type": "fighting",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "self": {"boosts": {"def": -1, "spd": -1}},
        "secondary": None,
    },
    "direclaw": {
        "base_power": 80,
        "type": "poison",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 50, "on_hit": "may poison, paralyze, or sleep target"},
    },
    "coaching": {
        "base_power": 0,
        "type": "fighting",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "adjacentAlly",
        "pp": 10,
        "flags": {"bypasssub": 1},
        "boosts": {"atk": 1, "def": 1},
        "secondary": None,
    },
    "drumbeating": {
        "base_power": 80,
        "type": "grass",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 100, "boosts": {"spe": -1}},
    },
    "stompingtantrum": {
        "base_power": 75,
        "type": "ground",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "if last move failed, power doubles",
        "secondary": None,
    },
    "blizzard": {
        "base_power": 110,
        "type": "ice",
        "category": "special",
        "priority": 0,
        "accuracy": 70,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1, "wind": 1},
        "on_modify_move": "if hail/snow, accuracy is 100",
        "secondary": {"chance": 10, "status": "frz"},
    },
    "auroraveil": {
        "base_power": 0,
        "type": "ice",
        "category": "status",
        "priority": 0,
        "accuracy": True,
        "target": "allySide",
        "pp": 20,
        "flags": {"snatch": 1},
        "on_try": "if hail/snow",
        "side_condition": "auroraveil",
        "secondary": None,
    },
    "rockslide": {
        "base_power": 75,
        "type": "rock",
        "category": "physical",
        "priority": 0,
        "accuracy": 90,
        "target": "allAdjacentFoes",
        "pp": 10,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 30, "volatileStatus": "flinch"},
    },
    "extremespeed": {
        "base_power": 80,
        "type": "normal",
        "category": "physical",
        "priority": 2,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "dragonclaw": {
        "base_power": 80,
        "type": "dragon",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": None,
    },
    "leafstorm": {
        "base_power": 130,
        "type": "grass",
        "category": "special",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "self": {"boosts": {"spa": -2}},
        "secondary": None,
    },
    "sleeppowder": {
        "base_power": 0,
        "type": "grass",
        "category": "status",
        "priority": 0,
        "accuracy": 75,
        "target": "normal",
        "pp": 15,
        "flags": {"powder": 1, "protect": 1, "reflectable": 1, "mirror": 1},
        "status": "slp",
        "secondary": None,
    },
    "overheat": {
        "base_power": 130,
        "type": "fire",
        "category": "special",
        "priority": 0,
        "accuracy": 90,
        "target": "normal",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "self": {"boosts": {"spa": -2}},
        "secondary": None,
    },
    "burningjealousy": {
        "base_power": 70,
        "type": "fire",
        "category": "special",
        "priority": 0,
        "accuracy": 100,
        "target": "allAdjacentFoes",
        "pp": 5,
        "flags": {"protect": 1, "mirror": 1},
        "secondary": {"chance": 100, "on_hit": "if target had stats boosted this turn, burns it"},
    },
    "icespinner": {
        "base_power": 80,
        "type": "ice",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_hit": "removes terrain",
        "secondary": None,
    },
    "ironhead": {
        "base_power": 80,
        "type": "steel",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 15,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "secondary": {"chance": 30, "volatileStatus": "flinch"},
    },
    "suckerpunch": {
        "base_power": 70,
        "type": "dark",
        "category": "physical",
        "priority": 1,
        "accuracy": 100,
        "target": "normal",
        "pp": 5,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_try": "fails if target is not preparing an attack",
        "secondary": None,
    },
    "assurance": {
        "base_power": 60,
        "type": "dark",
        "category": "physical",
        "priority": 0,
        "accuracy": 100,
        "target": "normal",
        "pp": 10,
        "flags": {"contact": 1, "protect": 1, "mirror": 1},
        "on_base_power": "if target has already taken damage this turn, power doubles",
        "secondary": None,
    },
}
